Simulating the globe tossing experiment

```{r}
library(brms)
library(ggplot2)
library(tidyverse)
library(tidybayes)
library(purrr)
```

Grid approximation

```{r}

n_gridpts <- 1001
n_success <- 6
n_trials <- 9

d <- tibble(
  p_grid = seq(from=0, to=1, length.out = n_gridpts),
  prior = 1 # a flat unirom prior
) %>%
  mutate(likelihood=dbinom(x = n_success, size = n_trials, prob = p_grid)) %>%
  mutate(posterior=(likelihood*prior)/sum(likelihood*prior))

glimpse(d)
```

Plotting posterior probability

```{r}

d %>%
  ggplot(aes(x=p_grid)) +
  geom_ribbon(aes(ymin=0, ymax=posterior), color='grey67', fill='grey67') +
  geom_point(data = . %>% filter(p_grid %in% c(seq(from = .1, to = .9, by = .1), 3 / 10)),
             aes(y = posterior)) +
  geom_segment(data = . %>% filter(p_grid %in% c(seq(from = .1, to = .9, by = .1), 3 / 10)), 
               aes(xend = p_grid,y = 0, yend = posterior, size = posterior),
               color = "grey33", show.legend = F) + 
  scale_size_continuous(range = c(0, 1)) +
  scale_x_continuous("probability of water", breaks = c(0:10) / 10) +
  scale_y_continuous(NULL, breaks = NULL) +
  theme(panel.grid = element_blank()) +
  annotate(geom = "text", x = .08, y = .0025, label = "Posterior probability")

```

Sampling from the posterior

```{r}

n_samples <- 1e4

samples <- d %>% 
              sample_n(n_samples, replace = T, weight = posterior) %>%
              mutate(w=purrr::map_dbl(.x = p_grid, .f = rbinom, n=1, size=9))

summary(samples)
```